# Generated by Django 4.1.7 on 2023-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_in_group',
            field=models.CharField(default='', max_length=100, verbose_name='Количество учеников в группе'),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_duration',
            field=models.CharField(default='', max_length=100, verbose_name='Длительность обучения'),
        ),
    ]
