# Generated by Django 4.1.7 on 2023-03-28 09:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_course_students_in_group_alter_course_study_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_for_second_month',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание второго месяца статьи', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='has_checkbox',
            field=models.BooleanField(default=False, help_text='Включить, если у описания статьи есть переключение между месяцами'),
        ),
    ]
