# Generated by Django 4.1.7 on 2023-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_course_content_for_second_month_course_has_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_duration_2',
            field=models.CharField(default='', help_text='Длительность обучения для второго месяца', max_length=100, verbose_name='Длительность обучения'),
        ),
    ]
