# Generated by Django 4.1.7 on 2023-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_course_study_duration_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='study_duration_2',
            field=models.CharField(blank=True, default='', help_text='Длительность обучения для второго месяца', max_length=100, null=True, verbose_name='Длительность обучения'),
        ),
    ]
