# Generated by Django 4.1.7 on 2023-03-28 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_course_study_duration_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя мастера')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание мастера')),
            ],
        ),
    ]
