# Generated by Django 4.1.7 on 2023-03-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
    ]
