# Generated by Django 4.1.7 on 2023-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_course_options_alter_master_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/masters/', verbose_name='Фото мастера'),
        ),
    ]
