# Generated by Django 4.1.7 on 2023-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_master_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/",
                verbose_name="Фотка для заставки",
            ),
        ),
    ]
