# Generated by Django 4.1.7 on 2023-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_course_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Данное поле заполняется само при добавлении названия курса",
            ),
        ),
    ]
