# Generated by Django 4.1.7 on 2023-04-02 16:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_alter_newitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newitem",
            name="short_descr",
            field=ckeditor.fields.RichTextField(
                default="", verbose_name="Короткое описание новости"
            ),
        ),
        migrations.AlterField(
            model_name="newitem",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Полное описание новости"),
        ),
        migrations.AlterField(
            model_name="newitem",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания статьи"),
        ),
    ]
