# Generated by Django 4.1.7 on 2023-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_newitem_short_descr_alter_newitem_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newitem",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, verbose_name="Название новости на латинице"
            ),
        ),
    ]
