# Generated by Django 4.1.7 on 2023-04-02 17:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_delete_newitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название новости"),
                ),
                (
                    "short_descr",
                    ckeditor.fields.RichTextField(
                        default="", verbose_name="Короткое описание новости"
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        verbose_name="Полное описание новости"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Фото новости")),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Дата создания статьи"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Название новости на латинице",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["pk"],
            },
        ),
    ]
