# Generated by Django 4.1.7 on 2023-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_alter_newitem_image_alter_newitem_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newitem",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Фото новости"),
        ),
    ]
