# Generated by Django 4.1.7 on 2023-04-04 08:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_newitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_for_second_month_ru',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание второго месяца статьи', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_for_second_month_uz',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание второго месяца статьи', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='study_duration_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Длительность обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_duration_uz',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Длительность обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='master',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Имя мастера'),
        ),
        migrations.AddField(
            model_name='master',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Имя мастера'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание новости'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание новости'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='short_descr_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Короткое описание новости'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='short_descr_uz',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Короткое описание новости'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='title_ru',
            field=models.CharField(max_length=350, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='newitem',
            name='title_uz',
            field=models.CharField(max_length=350, null=True, verbose_name='Название новости'),
        ),
    ]
