# Generated by Django 4.2 on 2023-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_course_content_for_second_month_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students_in_group_ru",
            field=models.CharField(
                default="",
                max_length=100,
                null=True,
                verbose_name="Количество учеников в группе",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="students_in_group_uz",
            field=models.CharField(
                default="",
                max_length=100,
                null=True,
                verbose_name="Количество учеников в группе",
            ),
        ),
    ]
