# Generated by Django 4.2 on 2023-04-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_course_students_in_group_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="content_for_second_month",
        ),
        migrations.RemoveField(
            model_name="course",
            name="content_for_second_month_ru",
        ),
        migrations.RemoveField(
            model_name="course",
            name="content_for_second_month_uz",
        ),
        migrations.RemoveField(
            model_name="course",
            name="study_duration_2",
        ),
    ]
