# Generated by Django 4.2 on 2023-04-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_course_content_for_second_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_checkbox',
        ),
    ]
